### ISSUE TITLE
Aware of pub.dartlang.org/packages/pub_semver?

### ISSUE THREAD

**Issue by kevmoo** [dartninja/version#1]
https://pub.dartlang.org/packages/pub_semver

There are some differences w/ the full semver spec – might be interesting to look at

**Comment by sanmadjack** [comment]
I am aware, but thanks for putting the info out there. This project strives to be exactly like the semver rules, so pub_semver is different but does serve its purpose.

**Comment by kevmoo** [comment]
Cool!

A friendly idea: note this difference in the README. 😄

**Comment by sanmadjack** [comment]
The readme already does say it's compliant with the semver spec. Are you saying to call out that it's different from pub_semver in the readme?

**Comment by kevmoo** [comment]
Just an idea – because we use pub_semver many places in our ecosystem. If
folks want to process pub versions specifically, it'd be good to be aware
of...

...just an idea :-)

**Comment by kevmoo** [comment]
Cool, thanks!

**Comment by sanmadjack** [comment]
Only took a year :)
