### ISSUE TITLE
Version.parse(String? version) should be Version.parse(String version) 

### ISSUE THREAD

**Issue by PoeMcMoe** [dartninja/version#12]
Why accept a nullable parameter if the method is going to throw when the parameter is null?

**Comment by sanmadjack** [comment]
I agree. Version 2.0.1, just published, has this change.

**Comment by mdccxv** [comment]
@sanmadjack 2.0.1 should really be 3.0.0, as this a breaking change. There are libraries and projects that rely on
`version: ">=2.0.0 <3.0.0"`
and it causes those to fail. One such example is `git_cli`.

edit: I'd suggest reverting this change in version `2.0.3` and reintroducing in `3.0.0`, that should make the least impact on everybody using this as a dependency
