### ISSUE TITLE
Version 2.0.1 introduces a breaking change. Should be 3.0.0

### ISSUE THREAD

**Issue by mdccxv** [dartninja/version#14]
2.0.1 should really be 3.0.0, as that version introduces a breaking change. There are libraries and projects that follow and rely on semantic versioning and have this dependencies set as:
`version: ">=2.0.0 <3.0.0"`
and it causes those to fail.

Maybe it's worth reverting this change in version 2.0.3 and reintroducing it in 3.0.0?
That should make the least impact on everybody using this package as their dependency

**Comment by sanmadjack** [comment]
You're right, I hadn't considered that. 2.0.3 has just been pushed reverting the change. I'm presuming that this has affected you, can you update and confirm that it is resolved for you before I push 3.0.0?

**Comment by mdccxv** [comment]
Yes, it did impact me and yes, it is fixed now.
Thank you :)

**Comment by sanmadjack** [comment]
Great. 3 has been pushed, so that's that.
