### ISSUE TITLE
provide ability to increment beta version.

### ISSUE THREAD

**Issue by bsutton** [dartninja/version#3]
I need the ability to increment beta/Dev versions as well.

So
1.0.0-beta.1 becomes 1.0.0-beta.2

**Comment by bsutton** [comment]
Looking at the spec i would expect the increment function to search from the right for a numerical value and increment that value.

If no numerical value is found then a .1 is appended.

If the version is not a pre release then the increment fails.

**Comment by sanmadjack** [comment]
This will be present in the next stable build
