### ISSUE TITLE
Upgrading to null safety?

### ISSUE THREAD

**Issue by larryaasen** [dartninja/version#5]
Thanks for creating this package. We have been using this `version` package in the [upgrader](https://pub.dev/packages/upgrader) package and now are migrating to null safety. I see there are 12 total packages using this package, and [noted on pub.dev](https://pub.dev/packages?q=dependency%3Aversion). Are you planning to upgrade this package to null safety?

**Comment by sanmadjack** [comment]
When I have the time to do so, yes. I would also accept a pull request.

**Comment by larryaasen** [comment]
Created PR https://github.com/dartninja/version/pull/6

**Comment by sanmadjack** [comment]
This is available in the 2.0.0-nullsafety pre-release. It can be depended on with ^2.0.0-0. I'm leaving this ticket open until null safety is in the stable SDK, then I'll create a stable update and deploy.

**Comment by larryaasen** [comment]
The latest null safety version looks good and I've published a pre-release of [upgrader](https://pub.dev/packages/upgrader/versions/3.0.0-nullsafety.2) using it. Thanks.

Now, I am getting this error as I attempt to publish a normal release of upgrader:
`Packages dependent on a pre-release of another package should themselves be published as a pre-release version. If this package needs version version 2.0.0-nullsafety, consider publishing the package as a pre-release instead.`

When the version package has a normal release of null safety, we can then publish our own packages as a normal release.

**Comment by larryaasen** [comment]
@sanmadjack Any plans to release a final null safety update so we can use it?

**Comment by sanmadjack** [comment]
Yeah, I'm downloading latest dart now to run some final checks.

**Comment by sanmadjack** [comment]
2.0 final has been pushed with null safety. Please open another ticket if you encounter any issues.
